Controllers/LanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_ef.Models;

namespace mvc_ef.Controllers
{
    public class LanguageController : Controller
    {
        private readonly SqliteContext _context;

        public LanguageController(SqliteContext context)
        {
            _context = context;
        }

        // GET: Language
        public IActionResult Index()
        {
            return View( _context.Languages);
        }

        // GET: Language/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language =  _context.Languages
                .FirstOrDefault(m => m.Id == id);

            if (language == null)
            {
                return NotFound();
            }

            return View(language);
        }

        // GET: Language/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Language/Create
	[HttpPost]
	public IActionResult Create([Bind("LanguageName")] Language language)
        {
            if (ModelState.IsValid)
            {
                _context.Add(language);
                 _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Language/Edit/5
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language =  _context.Languages.Find(id);

            if (language == null)
            {
                return NotFound();
            }
            return View(language);
        }

        // POST: Language/Edit/5
        [HttpPost]
        public  IActionResult Edit(int id, [Bind("Id,LanguageName")] Language language)
        {
	    if (!LanguageExists(language.Id))
	    {
		return NotFound();
	    }

            if (id != language.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
		_context.Update(language);
		 _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        // GET: Language/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language =  _context.Languages
                .FirstOrDefault(m => m.Id == id);

            if (language == null)
            {
                return NotFound();
            }

            return View(language);
        }

        // POST: Language/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var language =  _context.Languages.Find(id);
            _context.Languages.Remove(language);
	    _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool LanguageExists(int id)
        {
            return _context.Languages.Any(e => e.Id == id);
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_ef.Models;
using System.Text.Encodings.Web;

namespace mvc_ef.Controllers
{
    public class PersonController : Controller
    {
        private readonly SqliteContext _context;

        public PersonController(SqliteContext context)
        {
            _context = context;
        }

        // GET: Person
        public IActionResult Index()
        {
            var sqliteContext = _context.People.Include(p => p.City).ThenInclude(c => c.Country);
            return View(sqliteContext);
        }

        // GET: Person/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person =  _context.People
                .Include(p => p.City)
		.ThenInclude(c => c.Country)
                .FirstOrDefault(m => m.Id == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // GET: Person/Create
        public IActionResult Create()
        {
            ViewData["Cities"] = new SelectList(_context.Cities, "Id", "CityName");
            return View();
        }

        // POST: Person/Create
        [HttpPost]
        public IActionResult Create([Bind("PersonName,CityId")] Person person)
        {
            if (ModelState.IsValid)
            {
                _context.Add(person);
		_context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cities"] = new SelectList(_context.Cities, "Id", "CityName", person.City.CityName);
	    return View(person);
        }

        // GET: Person/Edit/5
        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
	 
            var person =  _context.People.Include(c => c.City).FirstOrDefault(p => p.Id == id);

            if (person == null)
            {
                return NotFound();
            }

	    ViewData["Cities"] = new SelectList(_context.Cities, "Id", "CityName", person.City.CityName);
            return View(person);
        }

        // POST: Person/Edit/5
        [HttpPost]
        public  IActionResult Edit(int id, [Bind("Id,PersonName,CityId")] Person person)
        {
	    if (!PersonExists(person.Id))
	    {
		return NotFound();
	    }
            if (id != person.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
		_context.Update(person);
		_context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Cities"] = new SelectList(_context.Cities, "Id", "CityName", person.City.CityName);
            return View(person);
        }

        // GET: Person/Delete/5
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person =  _context.People
                .Include(p => p.City)
                .FirstOrDefault(m => m.Id == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            var person =  _context.People.Find(id);
            _context.People.Remove(person);
	    _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id)
        {
            return _context.People.Any(e => e.Id == id);
        }
    }
}

Controllers/PersonLanguageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using mvc_ef.Models;
using System.Text.Encodings.Web;

namespace mvc_ef.Controllers
{
    public class PersonLanguageController : Controller
    {
        private readonly SqliteContext _context;

        public PersonLanguageController(SqliteContext context)
        {
            _context = context;
        }

	// PersonLanguage/Edit/5
	public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person =  _context.People
                .Include(p => p.Languages)
                .FirstOrDefault(m => m.Id == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

	// PersonLanguage/Add/5
	public IActionResult Add(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

	    var person =  _context.People
                .Include(p => p.Languages)
		.FirstOrDefault(m => m.Id == id);
		
	    var personLanguages = person.Languages;
	    var languages =  _context.Languages.ToList().Except(personLanguages);

            if (personLanguages == null)
            {
                return NotFound();
            }

	    ViewData["PersonId"] = id;
	    ViewData["PersonName"] = person.PersonName;
	    return View(languages);
        }

	// GET:PersonLanguage/AddLanguage/5
	public IActionResult AddLanguage(int? id, int languageId)
        {
            if (id == null)
            {
                return NotFound();
            }

            var language =  _context.Languages.Find(languageId);
	    var person = _context.People.Find(id);
            if (language == null)
            {
                return NotFound();
            }
	    ViewData["PersonId"] = id;
	    ViewData["PersonName"] = person.PersonName;
	    return View(language);
        }

        // POST: PersonLangauge/AddLanguage/5
	[HttpPost, ActionName("AddLanguage")]
        public IActionResult AddLanguageConfirmed(int id, int languageId)
        {
	    var person = _context.People.Include(p => p.Languages).FirstOrDefault(p => p.Id == id);
	    var languageToAdd = _context.Languages.FirstOrDefault(l => l.Id == languageId);
	    person.Languages.Add(languageToAdd);
	    _context.SaveChanges();
	    return RedirectToAction("Edit", new { id = id });
        }

	// GET: PersonLanguage/DeleteLanguage/5
        public IActionResult DeleteLanguage(int? languageId, int id)
        {
            if (languageId == null)
            {
                return NotFound();
            }

	    var language = _context.Languages.Single(u => u.Id == languageId);
	    var person = _context.People.Single(p => p.Id == id);

            if (language == null)
            {
                return NotFound();
            }
	    ViewData["PersonId"] = id;
	    ViewData["PersonName"] = person.PersonName;
            return View(language);
        }

        // POST: PersonLangauge/DeleteLanugae/5
        [HttpPost, ActionName("DeleteLanguage")]
        public IActionResult DeleteLanguage(int id, int languageId)
        {
	    var person = _context.People.Include(p => p.Languages).FirstOrDefault(p => p.Id == id);
	    var languageToRemove = _context.Languages.FirstOrDefault(l => l.Id == languageId);
	    person.Languages.Remove(languageToRemove);
            _context.SaveChanges();
            return RedirectToAction("Edit", new { id = id });
        }

	private bool PersonExists(int id)
        {
            return _context.People.Any(e => e.Id == id);
        }
    }
}

Views/PersonLanguage/Add.cshtml
@model IEnumerable<mvc_ef.Models.Language>
    @{
	ViewData["Title"] = "Add Languages";
    }

    <h1>@ViewData["personName"]</h1>

    <table class="table">
	<thead>
            <tr>
		<th>
                    @Html.DisplayNameFor(model => model.LanguageName)
		</th>
		<th>

		</th>
		</th>
            </tr>
	</thead>
	<tbody>
	    @foreach (var item in Model)
	    {
		<tr>
		<td>
	    	@Html.DisplayFor(modelItem => item.LanguageName)
		</td>
		<td>
                    <a asp-action="AddLanguage" asp-route-languageId="@item.Id" asp-route-id=@ViewData["personId"]>Add</a>
		</td>
		</tr>
		}
	</tbody>
    </table>
    <div>
	<a asp-action="Edit" asp-route-id=@ViewData["personId"]>Back to List</a>
    </div>

Views/PersonLanguage/AddLanguage.cshtml
@model mvc_ef.Models.Language

@{
    ViewData["Title"] = "Add Language";
}

<h1>Add</h1>

<h3>Are you sure you want to Add @Model.LanguageName (@Model.Id)</h3>
<div>
    <h4>to @ViewData["PersonName"] (@ViewData["PersonId"])</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
        
        </dt>
        <dd class = "col-sm-10">
        
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LanguageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LanguageName)
        </dd>
    </dl>
    
    <form asp-action="AddLanguage" >
        <input type="submit" value="Add" class="btn btn-primary" asp-route-languageId="@Model.Id" asp-route-id=@ViewData["PersonId"] /> |
        <a asp-action="Edit" asp-controller="PersonLanguage" asp-route-id=@ViewData["PersonId"]>Back to Language List</a>
    </form>
</div>

Views/PersonLanguage/Delete.cshtml
@model mvc_ef.Models.Language

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete @Model.LanguageName from?</h3>
<div>
    <h4>Person Id is @ViewData["PersonId"]</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
        
        </dt>
        <dd class = "col-sm-10">
        
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LanguageId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LanguageName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for=@Model.LanguageId />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-controller="PersonLanguage" asp-route-id=@ViewData["PersonId"]>Back to Language List</a>
    </form>
</div>

Views/PersonLanguage/DeleteLanguage.cshtml
@model mvc_ef.Models.Language

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete @Model.LanguageName from?</h3>
<div>
    <h4>@ViewData["PersonName"] (@ViewData["PersonId"])</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
        
        </dt>
        <dd class = "col-sm-10">
        
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LanguageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LanguageName)
        </dd>
    </dl>
    
    <form asp-action="DeleteLanguage">
        <input type="submit" value="Delete" class="btn btn-danger" asp-route-languageId="@Model.Id" asp-route-id=@ViewData["PersonId"] /> |
        <a asp-action="Edit" asp-controller="PersonLanguage" asp-route-id=@ViewData["PersonId"]>Back to Language List</a>
    </form>
</div>

Views/PersonLanguage/Edit.cshtml
@model mvc_ef.Models.Person

    @{
	ViewData["Title"] = "Languages";
    }

    <h1>@Model.PersonName</h1>

    <p>
	<a asp-action="Add" asp-route-id="@Model.Id">Add Language</a>
    </p>
    <table class="table">
	<thead>
            <tr>
		<th>
                    @Html.DisplayNameFor(model => model.Languages)
		</th>
		<th>

		</th>
		</th>
            </tr>
	</thead>
	<tbody>
	    @foreach (var item in Model.Languages)
	    {
		<tr>
		<td>
	    	@Html.DisplayFor(modelItem => item.LanguageName)
		</td>
		<td>
                    <a asp-action="DeleteLanguage" asp-route-languageId="@item.Id" asp-route-id="@Model.Id">Delete</a>
		</td>
		</tr>
		}
	</tbody>
    </table>
    <div>
	<a asp-controller="Person" asp-action="Index">Back to List</a>
    </div>

Views/PersonLanguage/Index.cshtml
@model mvc_ef.Models.Person

    @{
	ViewData["Title"] = "Languages";
    }

    <h1>@Model.PersonName</h1>

    <p>
	<a asp-action="Create">Add Langauge</a>
    </p>
    <table class="table">
	<thead>
            <tr>
		<th>
                    @Html.DisplayNameFor(model => model.Languages)
		</th>
		<th>

		</th>
		</th>
            </tr>
	</thead>
	<tbody>
	    @foreach (var item in Model.Languages)
	    {
		<tr>
		<td>
	    	@Html.DisplayFor(modelItem => item.LanguageName)
		</td>
		<td>
                    <a asp-action="Delete" asp-route-languageId="@item.LanguageId" asp-route-id="@Model.PersonId">Delete</a>
		</td>
            </tr>
	    }
	</tbody>
    </table>

Views/PersonLanguage/IndexAdd.cshtml
@model mvc_ef.Models.Person

    @{
	ViewData["Title"] = "Languages";
    }

    <h1>@Model.PersonName</h1>

    <table class="table">
	<thead>
            <tr>
		<th>
                    @Html.DisplayNameFor(model => model.Languages)
		</th>
		<th>

		</th>
		</th>
            </tr>
	</thead>
	<tbody>
	    @foreach (var item in Model.Languages)
	    {
		<tr>
		<td>
	    	@Html.DisplayFor(modelItem => item.LanguageName)
		</td>
		<td>
                    <a asp-action="Add" asp-route-languageId="@item.LanguageId" asp-route-id="@Model.PersonId">Add</a>
		</td>
		</tr>
		}
	</tbody>
    </table>
    <div>
	<a asp-action="IndexDelete" asp-route-id="@Model.PersonId">Back to List</a>
    </div>

Views/PersonLanguage/Language.cshtml
@model mvc_ef.Models.Person

    @{
	ViewData["Title"] = "Languages";
    }

    <h1>@Model.PersonName</h1>

    <p>
	<a asp-action="Create">Add Langauge</a>
    </p>
    <table class="table">
	<thead>
            <tr>
		<th>
                    @Html.DisplayNameFor(model => model.Languages)
		</th>
		<th>

		</th>
		</th>
            </tr>
	</thead>
	<tbody>
	    @foreach (var item in Model.Languages)
	    {
		<tr>
		<td>
	    	@Html.DisplayFor(modelItem => item.LanguageName)
		</td>
		<td>
                    <a asp-action="Edit" asp-route-id="@item.LanguageId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.LanguageId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.LanguageId">Delete</a> |
		</td>
            </tr>
	    }
	</tbody>
    </table>